from rest_framework import serializers
from .models import Product

class ProductSerializer(serializers.ModelSerializer):
    discount = serializers.SerializerMethodField() # This line defines a new field called 'discount' in the ProductSerializer, which is a SerializerMethodField. This means that the value for this field will be determined by a method in the serializer, rather than being directly tied to a model field. The method that will be called to get the value for this field is defined as 'get_discount', which is a method in the Product model that returns a fixed value ("122"). By using SerializerMethodField, we can include computed or dynamic values in our serialized output without needing to store them in the database or define them as model fields.
    class Meta:
        model = Product
        # fields = ['id', 'title', 'content', 'price', 'sale_price', 'get_discount'] # We include the 'sale_price' and 'discount' fields in the serializer, even though they are not actual model fields. This allows us to include these computed properties in the serialized output when we return the data from our API views. The 'sale_price' is a property method defined in the Product model that calculates a discounted price, while 'discount' is a method that returns a fixed value. By including them in the serializer, we can easily access these values in our API responses without needing to modify the underlying model or database schema.
# when using a regular method in the serializer, which has no @property, Django REST Framework will ((((try))) to call it as a method, which means it will execute the method and return its result in the serialized data. In this case, the 'get_discount' method will be called when the serializer is used, and its return value ("122") will be included in the serialized output under the 'get_discount' field. This allows us to include dynamic or computed values in our API responses without needing to store them in the database. But, this is not a common practice, and it's generally better to use @property for such cases, as it makes it clear that the value is computed and not stored in the database.
# and if we want to include a method that is not a property, we can use the SerializerMethodField in the serializer, which allows us to define a method in the serializer that will be called to get the value for that field. For example, we could define a method called 'get_discount' in the ProductSerializer and use it to return the discount value, and then include it in the fields list as 'discount = serializers.SerializerMethodField()'. This way, we can keep our model clean and still include computed values in our API responses.
        fields = ['id', 'title', 'content', 'price', 'sale_price', 'discount']
    
    def get_discount(self, obj):
        return obj.get_discount() # This method is defined in the ProductSerializer to provide the value for the 'discount' field, which is a SerializerMethodField. The method takes two parameters: 'self', which refers to the instance of the serializer, and 'obj', which is the instance of the Product model being serialized. Inside the method, we call the 'get_discount' method on the 'obj' (the Product instance) to retrieve the discount value, which is then returned as the value for the 'discount' field in the serialized output. This allows us to include dynamic or computed values in our API responses without needing to store them in the database or define them as model fields.
    